name: Python application

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main , development ]

jobs:
    linux:
      name: linux build
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Building with pyinstaller
          run: |
            cd src
            pyinstaller --onefile Polynomial-solver.py
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: 'linux-x64' 
            path: dist
          
    windows:
      name: windows build
      strategy:
        matrix:
          architecture: [x86, x64]
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
            architecture: ${{matrix.architecture}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Building with pyinstaller
          run: |
            cd src
            pyinstaller --onefile Polynomial-solver.py
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: windows-${{matrix.architecture}}
            path: dist
        
    macos:
      name: macos build
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Building with pyinstaller
          run: |
            cd src
            pyinstaller --onefile Polynomial-solver.py
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: 'macos-x64' 
            path: dist 
